---
title: "Naive Bayes Data Iris"
output:
  html_document:
    df_print: paged
---
```{r}
#import library yang dibutuhkan
library(e1071)
library(caret)
library(caTools)
```


```{r}
#import dataset yang akan digunakan
dataIris = read.csv(file = "heart_failure.csv", stringsAsFactors = TRUE)
```


```{r}
#cek apakah dataset berhasil di-import
head(dataIris)
```


```{r}
#mengubah variabel input yang kontinyu menjadi diskrit
for (i in c(1, 3, 5, 7, 8, 9, 12)) {
  tempIris <- dataIris
  tempQ <- quantile(tempIris[,i],c(0/3,1/3,2/3))
  dataIris[which(tempIris[,i] >= tempQ[1]),i] <- "rendah"
  dataIris[which(tempIris[,i] >= tempQ[2]),i] <- "sedang"
  dataIris[which(tempIris[,i] >= tempQ[3]),i] <- "tinggi"
}

for (i in c(2, 4, 6, 10, 11)) {
  tempIris <- dataIris
  tempQ <- quantile(tempIris[,i],c(0/2,1/2))
  dataIris[which(tempIris[,i] >= tempQ[1]),i] <- "ya"
  dataIris[which(tempIris[,i] >= tempQ[2]),i] <- "tidak"
}
head(dataIris)
```


```{r}
#buat data training dan testing

split = sample.split(dataIris$DEATH_EVENT, SplitRatio = 0.8)

data_training = subset(dataIris, split == TRUE)
data_testing = subset(dataIris, split == FALSE)
```


```{r}
#membuat model Naive Bayes model
Naive_Bayes_Model=naiveBayes(DEATH_EVENT~., data=data_training)
```


```{r}
#Predict the data_testing
vector_prediction = predict(Naive_Bayes_Model, data_testing)
vp = vector_prediction
vp
```


```{r}
#tes akurasi menggunakan confusionMatrix
confusionMatrix(as.factor(vp), as.factor(data_testing$DEATH_EVENT))
```

